# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/NewTempImg.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewTempImg(object):
    def setupUi(self, NewTempImg):
        NewTempImg.setObjectName("NewTempImg")
        NewTempImg.resize(539, 269)
        self.gridLayout = QtWidgets.QGridLayout(NewTempImg)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lblName = QtWidgets.QLabel(NewTempImg)
        self.lblName.setObjectName("lblName")
        self.verticalLayout.addWidget(self.lblName)
        self.editName = QtWidgets.QLineEdit(NewTempImg)
        self.editName.setObjectName("editName")
        self.verticalLayout.addWidget(self.editName)
        self.lblText = QtWidgets.QLabel(NewTempImg)
        self.lblText.setObjectName("lblText")
        self.verticalLayout.addWidget(self.lblText)
        self.editText = QtWidgets.QLineEdit(NewTempImg)
        self.editText.setObjectName("editText")
        self.verticalLayout.addWidget(self.editText)
        self.lblFont = QtWidgets.QLabel(NewTempImg)
        self.lblFont.setObjectName("lblFont")
        self.verticalLayout.addWidget(self.lblFont)
        self.editFont = QtWidgets.QLineEdit(NewTempImg)
        self.editFont.setReadOnly(True)
        self.editFont.setObjectName("editFont")
        self.verticalLayout.addWidget(self.editFont)
        self.lblWidth = QtWidgets.QLabel(NewTempImg)
        self.lblWidth.setObjectName("lblWidth")
        self.verticalLayout.addWidget(self.lblWidth)
        self.spinWidth = QtWidgets.QSpinBox(NewTempImg)
        self.spinWidth.setMaximum(4096)
        self.spinWidth.setProperty("value", 314)
        self.spinWidth.setObjectName("spinWidth")
        self.verticalLayout.addWidget(self.spinWidth)
        self.lblHeight = QtWidgets.QLabel(NewTempImg)
        self.lblHeight.setObjectName("lblHeight")
        self.verticalLayout.addWidget(self.lblHeight)
        self.spinHeight = QtWidgets.QSpinBox(NewTempImg)
        self.spinHeight.setMaximum(4096)
        self.spinHeight.setProperty("value", 512)
        self.spinHeight.setObjectName("spinHeight")
        self.verticalLayout.addWidget(self.spinHeight)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewTempImg)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(NewTempImg)
        self.buttonBox.accepted.connect(NewTempImg.accept) # type: ignore
        self.buttonBox.rejected.connect(NewTempImg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewTempImg)

    def retranslateUi(self, NewTempImg):
        _translate = QtCore.QCoreApplication.translate
        NewTempImg.setWindowTitle(_translate("NewTempImg", "Generate Temp Image"))
        self.lblName.setText(_translate("NewTempImg", "Name"))
        self.lblText.setText(_translate("NewTempImg", "Text"))
        self.editText.setText(_translate("NewTempImg", "Temp"))
        self.lblFont.setText(_translate("NewTempImg", "Font Style"))
        self.lblWidth.setText(_translate("NewTempImg", "Width"))
        self.lblHeight.setText(_translate("NewTempImg", "Height"))
